Repository mawaqit/android-tv-app, pull requests merged in 2023-02, with the labels that each got.

#451 fix mosque background show the right image and darken the image
  lib/src/pages/home/widgets/mosque_background_screen.dart
Labels: bug

#457 show tomorrow times after isha
  lib/src/pages/home/widgets/SalahTimesBar.dart
  lib/src/services/mixins/mosque_helpers_mixins.dart
Labels: enhancement

#464 little improve the performance
  lib/src/helpers/StringUtils.dart
  lib/src/pages/home/sub_screens/AfterSalahAzkarScreen.dart
  lib/src/pages/home/sub_screens/AnnouncementScreen.dart
  lib/src/pages/home/sub_screens/IqamaSubScreen.dart
  lib/src/pages/home/sub_screens/IqamaaCountDownSubScreen.dart
  lib/src/pages/home/sub_screens/JumuaHadithSubScreen.dart
  lib/src/pages/home/widgets/AboveSalahBar.dart
  lib/src/pages/home/widgets/SalahInWidget.dart
  lib/src/pages/home/widgets/SalahItem.dart
  lib/src/pages/home/widgets/TimeWidget.dart
  lib/src/pages/home/widgets/offline_widget.dart
Labels: enhancement

#466 fix home time widget animations
  lib/src/helpers/Api.dart
  lib/src/pages/home/OfflineHomeScreen.dart
  lib/src/pages/home/widgets/CurrentTimeWidget.dart
  lib/src/pages/home/widgets/FadeInOut.dart
  lib/src/pages/home/widgets/HomeDateWidget.dart
  lib/src/pages/home/widgets/SalahInWidget.dart
  lib/src/pages/home/widgets/TimeWidget.dart
  lib/src/pages/home/workflow/normal_workflow.dart
  lib/src/services/mixins/mosque_helpers_mixins.dart
Labels: bug

#467 recheck the data each 1min
  lib/src/helpers/Api.dart
  lib/src/helpers/ApiInterceptor.dart
  lib/src/pages/home/widgets/offline_widget.dart
Labels: enhancement

#472 hide mosque info when flash message exist
  lib/src/pages/home/widgets/footer.dart
Labels: bug

#474 show flash message if no date
  lib/src/pages/home/widgets/FlashWidget.dart
  lib/src/pages/home/widgets/footer.dart
Labels: bug

#479 fix search api method
  lib/src/helpers/Api.dart
  lib/src/models/mosque.dart
Labels: bug

#485 Shrouk empty error
  lib/src/pages/home/widgets/SalahItem.dart
  lib/src/services/mixins/mosque_helpers_mixins.dart
Labels: bug

#490 extract weather icons font.ttf and use it show the right icons for the weather
  lib/src/helpers/weather_icons.dart
  lib/src/pages/home/widgets/HomeDateWidget.dart
  lib/src/pages/home/widgets/WeatherWidget.dart
Labels: bug

#501 fix connectivity widget
  lib/src/pages/home/widgets/offline_widget.dart
  lib/src/services/mixins/connectivity_mixin.dart
  lib/src/services/mosque_manager.dart
Labels: bug

#502 show black screen during salah time
  lib/src/pages/home/workflow/salah_workflow.dart
Labels: bug

#503 fix android build issue
  lib/src/helpers/weather_icons.dart
  pubspec.yaml
Labels: bug

#505 add default values for the backend response
  lib/src/models/announcement.dart
  lib/src/models/flash.dart
  lib/src/models/mosqueConfig.dart
  lib/src/models/times.dart
  lib/src/pages/home/sub_screens/AnnouncementScreen.dart
Labels: bug

#508 fix performance issues
  lib/src/developer_mode/TestSubScreens.dart
  lib/src/models/mosqueConfig.dart
  lib/src/pages/HomeScreen.dart
  lib/src/pages/SplashScreen.dart
  lib/src/pages/home/widgets/FadeInOut.dart
  lib/src/pages/home/widgets/FlashAnimation.dart
  lib/src/pages/home/widgets/FlashWidget.dart
  lib/src/pages/home/widgets/TimeWidget.dart
  lib/src/pages/home/widgets/mosque_background_screen.dart
  lib/src/services/mixins/weather_mixin.dart
Labels: bug

#510 remove usage of fixed directionalities
  lib/src/developer_mode/RandomHadithTest.dart
  lib/src/pages/home/sub_screens/AdhanSubScreen.dart
  lib/src/pages/home/sub_screens/normal_home.dart
  lib/src/pages/home/widgets/AboveSalahBar.dart
  lib/src/pages/home/widgets/CurrentTimeWidget.dart
  lib/src/pages/home/widgets/SalahItem.dart
  lib/src/pages/home/widgets/SalahTimesBar.dart
  lib/src/pages/home/widgets/TimeWidget.dart
  lib/src/pages/home/widgets/WeatherWidget.dart
Labels: bug

#511 highlign current adhan and iqama in adhan and iqama screens
  lib/src/pages/home/widgets/SalahTimesBar.dart
  lib/src/services/mixins/mosque_helpers_mixins.dart
Labels: content-update

#512 Handle shrouk time
  lib/src/pages/home/widgets/SalahInWidget.dart
  lib/src/pages/home/widgets/ShurukWidget.dart
  lib/src/services/mixins/mosque_helpers_mixins.dart
Labels: content-update

#513 handle jumuaAsDuhr from the api config
  lib/src/pages/home/sub_screens/normal_home.dart
Labels: content-update

#515 show valid day name on hijri dates
  lib/src/models/MawaqitHijriCalendar.dart
  lib/src/services/mixins/mosque_helpers_mixins.dart
Labels: bug

#524 fix text size in after adhan hadith
  lib/src/pages/home/sub_screens/AfterAdhanHadithSubScreen.dart
Labels: bug

#525 handle text size in jummua hadith screen
  lib/src/pages/home/sub_screens/AfterAdhanHadithSubScreen.dart
  lib/src/pages/home/sub_screens/JumuaHadithSubScreen.dart
Labels: bug, content-update

#526 fix home screen date format
  lib/src/helpers/DateUtils.dart
  lib/src/helpers/StringUtils.dart
  lib/src/models/MawaqitHijriCalendar.dart
  lib/src/pages/home/widgets/HomeDateWidget.dart
Labels: content-update

#528 Fix the home screen widgets opacity
  lib/main.dart
  lib/src/developer_mode/DrawerListTest.dart
  lib/src/models/MawaqitHijriCalendar.dart
  lib/src/pages/home/widgets/SalahItem.dart
  lib/src/pages/home/widgets/TimeWidget.dart
  lib/src/pages/onBoarding/widgets/LanuageSelectorWidget.dart
  lib/src/services/theme_manager.dart
  lib/src/widgets/MawaqitDrawer.dart
Labels: content-update

#533 implement screen for development to speed up the test phase
  lib/src/developer_mode/DrawerListTest.dart
  lib/src/pages/developer/DeveloperScreen.dart
  lib/src/pages/developer/widgets/number_input_widget.dart
  lib/src/pages/developer/widgets/selector_widget.dart
Labels: bug

#534 update footer background opacity
  lib/src/pages/home/widgets/footer.dart
Labels: enhancement

#537 highlight jumua with Duhr in int Friday
  lib/src/pages/home/sub_screens/normal_home.dart
  lib/src/services/mixins/mosque_helpers_mixins.dart
Labels: bug

#539 handle when the hijri date disabled from the config
  lib/src/pages/home/widgets/FadeInOut.dart
  lib/src/pages/home/widgets/HomeDateWidget.dart
Labels: bug

#543 hadith should take all available space
  lib/src/helpers/ApiInterceptor.dart
  lib/src/pages/home/OfflineHomeScreen.dart
  lib/src/pages/home/sub_screens/RandomHadithScreen.dart
  lib/src/pages/home/widgets/HomeDateWidget.dart
  lib/src/services/mosque_manager.dart
Labels: enhancement

#535 calculate imsak based on tomorrow times
  lib/src/services/mixins/mosque_helpers_mixins.dart
Labels: bug

#547 fix home footer widget color
  lib/src/pages/developer/DeveloperScreen.dart
  lib/src/pages/developer/widgets/number_input_widget.dart
  lib/src/pages/developer/widgets/selector_widget.dart
  lib/src/pages/home/widgets/HomeLogoVersion.dart
  lib/src/pages/home/widgets/MosqueInformationWidget.dart
  lib/src/pages/home/widgets/footer.dart
  lib/src/pages/home/workflow/salah_workflow.dart
  lib/src/services/mixins/mosque_helpers_mixins.dart
  lib/src/services/theme_manager.dart
Labels: bug

#551 fix before fajr handler
  lib/src/models/mosqueConfig.dart
  lib/src/pages/home/workflow/normal_workflow.dart
Labels: bug

#553 cache playable audio file to be used on offline mode
  lib/src/helpers/Api.dart
  lib/src/pages/home/sub_screens/AdhanSubScreen.dart
  lib/src/pages/home/sub_screens/AfterAdhanHadithSubScreen.dart
  lib/src/pages/home/sub_screens/IqamaSubScreen.dart
  lib/src/services/audio_manager.dart
  pubspec.yaml
Labels: bug

#561 add minimum iqama number into 3min
  lib/src/helpers/time_utils.dart
  lib/src/pages/home/sub_screens/IqamaSubScreen.dart
  lib/src/pages/home/workflow/salah_workflow.dart
  lib/src/services/mixins/mosque_helpers_mixins.dart
Labels: bug

#563 dont highlight shrouk
  lib/src/pages/home/widgets/ShurukWidget.dart
Labels: bug

#565 dont hilight duhr during jumua in mosque
  lib/src/pages/home/widgets/SalahTimesBar.dart
  lib/src/services/mixins/mosque_helpers_mixins.dart
Labels: bug

#567 fix after salah duaa screen auto text sizing
  lib/l10n/intl_en.arb
  lib/src/pages/home/sub_screens/AfterAdhanHadithSubScreen.dart
Labels: bug

#573 add kufi font into mawaqit footer
  lib/src/pages/home/widgets/FlashWidget.dart
  lib/src/widgets/MawaqitWebViewWidget.dart
Labels: bug

#576 handle when imsak is disabled when imsakBeforeFajr = 0
  lib/src/pages/home/widgets/ShurukWidget.dart
  lib/src/services/mixins/mosque_helpers_mixins.dart
Labels: bug

#578 536 jumua is not handled not highlighted i have shuruq highlighted instead countdown not ok no thikr etc
  lib/src/pages/home/sub_screens/AdhanSubScreen.dart
  lib/src/pages/home/sub_screens/AfterAdhanHadithSubScreen.dart
  lib/src/pages/home/sub_screens/IqamaSubScreen.dart
  lib/src/pages/home/widgets/SalahInWidget.dart
  lib/src/pages/home/widgets/SalahItem.dart
  lib/src/pages/home/widgets/SalahTimesBar.dart
  lib/src/pages/home/workflow/jumua_workflow_screen.dart
  lib/src/pages/home/workflow/salah_workflow.dart
  lib/src/services/audio_manager.dart
  lib/src/services/mixins/mosque_helpers_mixins.dart
Labels: bug

#579 handle random hadith caching manually
  lib/src/helpers/Api.dart
Labels: bug

#580 fix announcements screen
  lib/src/pages/home/sub_screens/AnnouncementScreen.dart
  lib/src/services/mixins/mosque_helpers_mixins.dart
Labels: bug

#581 fix azkar screen
  lib/src/helpers/repaint_boundaries.dart
  lib/src/pages/developer/widgets/selector_widget.dart
  lib/src/pages/home/sub_screens/AdhanSubScreen.dart
  lib/src/pages/home/sub_screens/AfterSalahAzkarScreen.dart
  lib/src/pages/home/sub_screens/AnnouncementScreen.dart
  lib/src/pages/home/sub_screens/IqamaSubScreen.dart
  lib/src/pages/home/sub_screens/IqamaaCountDownSubScreen.dart
  lib/src/pages/home/sub_screens/JumuaHadithSubScreen.dart
  lib/src/pages/home/sub_screens/RandomHadithScreen.dart
  lib/src/pages/home/sub_screens/normal_home.dart
  lib/src/pages/home/widgets/SalahTimesBar.dart
  lib/src/services/mosque_manager.dart
Labels: bug

#604 5Min before jumuaa shows normal home screen
  lib/src/enum/home_active_screen.dart
  lib/src/pages/home/sub_screens/JumuaHadithSubScreen.dart
  lib/src/pages/home/workflow/jumua_workflow_screen.dart
Labels: bug
