Repository mawaqit/android-tv-app, pull requests merged in 2023-04, with the labels that each got.

#720 fix time period on salah item widget
  lib/src/pages/home/widgets/SalahItem.dart
Labels: UX/UI

#722 Update AndroidManifest.xml
  android/app/src/main/AndroidManifest.xml
Labels: enhancement

#721 fix hadith invocation
  lib/src/pages/home/workflow/normal_workflow.dart
  lib/src/services/mixins/mosque_helpers_mixins.dart
Labels: enhancement

#732 add count down into the announcement list screen
  lib/src/pages/home/sub_screens/AnnouncementScreen.dart
Labels: UX/UI

#756 709 dua iftar assaim
  lib/src/pages/home/sub_screens/DuaaEftarScreen.dart
  lib/src/pages/home/widgets/workflows/WorkFlowWidget.dart
  lib/src/pages/home/widgets/workflows/repeating_workflow_widget.dart
  lib/src/pages/home/workflow/salah_workflow.dart
  lib/src/services/mixins/mosque_helpers_mixins.dart
Labels: feature request

#773 772 jumua and eid display bug
  lib/src/pages/home/widgets/SalahItem.dart
  lib/src/pages/home/widgets/SalahTimesBar.dart
Labels: bug
