Repository mawaqit/android-tv-app, pull requests merged in 2024-02, with the labels that each got.

#1018 Feat/mawqit for tv take the tv language as the app language by default
  lib/i18n/AppLanguage.dart
  lib/main.dart
  lib/src/const/config.dart
  lib/src/const/constants.dart
  lib/src/data/data_source/device_info_data_source.dart
  lib/src/data/repository/device_info_impl.dart
  lib/src/domain/model/device_info_model.dart
  lib/src/domain/repository/device_repository.dart
  lib/src/domain/usecase/on_boarding_usecase.dart
  lib/src/helpers/Api.dart
  lib/src/helpers/CrashlyticsWrapper.dart
  lib/src/helpers/LocaleHelper.dart
  lib/src/pages/onBoarding/OnBoardingScreen.dart
  lib/src/services/audio_manager.dart
  lib/src/state_management/on_boarding/on_boarding_notifier.dart
  lib/src/state_management/on_boarding/on_boarding_state.dart
  lib/src/widgets/MawaqitDrawer.dart
  pubspec.yaml
  test/src/data/constants_test.dart
Labels: feature request

#1014 Feat: add hamburger button to open drawer
  lib/src/pages/HomeScreen.dart
  lib/src/pages/home/widgets/mosque_background_screen.dart
  lib/src/pages/home/widgets/offline_widget.dart
Labels: feature request

#1024 Migrate: Integrate new `hijri-date` endpoint for Hijri date adjustment
  lib/src/helpers/Api.dart
  lib/src/models/hijri_data_config_model.dart
Labels: P0

#1021 Fix #1020 & add previous button to on-boarding workflow
  lib/l10n/intl_en.arb
  lib/src/pages/SettingScreen.dart
  lib/src/pages/onBoarding/OnBoardingScreen.dart
  lib/src/widgets/ScreenWithAnimation.dart
  lib/src/widgets/mawaqit_back_icon_button.dart
Labels: bug

#1026 FIX: Announcement are not displayed in infinite loop
  lib/src/models/mosque.dart
  lib/src/pages/home/sub_screens/AnnouncementScreen.dart
  lib/src/pages/home/widgets/AboveSalahBar.dart
  lib/src/pages/home/widgets/workflows/announcement_workflow.dart
  lib/src/services/mixins/mosque_helpers_mixins.dart
  lib/src/state_management/workflow/announcement_workflow.dart
  lib/src/state_management/workflow/video_workflow_state.dart
  lib/src/state_management/workflow/workflow_notifier.dart
Labels: bug

#1044 fix: Localization Access in PortraitNormalHome produces Assertion Error
  lib/src/pages/times/normal_home/portrait_normal_home.dart
Labels: bug
