Repository mawaqit/android-tv-app, pull requests merged in 2024-05, with the labels that each got.

#1127 Fix/ resize app icon
  android/app/src/main/res/mipmap-xhdpi/ic_channel_2.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
Labels: bug

#1131 refactor: update app pop up
  lib/l10n/intl_en.arb
  lib/src/pages/times/normal_home/landscape_normal_home.dart
  lib/src/pages/times/normal_home/portrait_normal_home.dart
  lib/src/pages/times/turkish_home/landscape_turkish_home.dart
  lib/src/pages/times/turkish_home/portrait_turkish_home.dart
  lib/src/state_management/app_update/app_update_notifier.dart
  lib/src/widgets/show_update_alert.dart
Labels: enhancement

#1136 revert: announcement
  lib/main.dart
  lib/src/const/constants.dart
  lib/src/data/data_source/announcement_local_data_source.dart
  lib/src/data/data_source/announcement_remote_data_source.dart
  lib/src/data/repository/announcement_impl.dart
  lib/src/developer_mode/AnnouncementTest.dart
  lib/src/domain/repository/announcement_repository.dart
  lib/src/helpers/SharedPref.dart
  lib/src/helpers/image_helper.dart
  lib/src/helpers/riverpod_logger.dart
  lib/src/helpers/time_helper.dart
  lib/src/models/announcement.dart
  lib/src/pages/home/sub_screens/AnnouncementScreen.dart
  lib/src/services/mixins/mosque_helpers_mixins.dart
  lib/src/services/mosque_manager.dart
  lib/src/state_management/workflow/announcement_workflow/announcement_workflow_notifier.dart
  lib/src/state_management/workflow/announcement_workflow/announcement_workflow_state.dart
Labels: bug

#1154 Add albanian language support
  lib/l10n/intl_sq.arb
Labels: translation

#1155 fix: Fixing the bug that causes the Adhan screen to be skipped when the time is set.
  lib/src/pages/home/sub_screens/AdhanSubScreen.dart
Labels: bug
