Repository mawaqit/android-tv-app, pull requests merged in 2024-09, with the labels that each got.

#1302 feat: sorting the reciters alphabetically
  lib/src/data/data_source/quran/recite_remote_data_source.dart
  lib/src/data/data_source/quran/reciter_local_data_source.dart
  lib/src/data/repository/quran/recite_impl.dart
  lib/src/domain/repository/quran/recite_repository.dart
  lib/src/state_management/quran/recite/recite_notifier.dart
  test/unit/data_source/recite_local_data_source_test.dart
  test/unit/data_source/recite_remote_data_source_test.dart
Labels: feature request

#1295 feat: Add support for Warsh Quran
  lib/l10n/intl_en.arb
  lib/src/const/constants.dart
  lib/src/data/data_source/quran/download_quran_local_data_source.dart
  lib/src/data/data_source/quran/download_quran_remote_data_source.dart
  lib/src/data/data_source/quran/quran_reading_local_data_source.dart
  lib/src/data/repository/quran/quran_download_impl.dart
  lib/src/data/repository/quran/quran_reading_impl.dart
  lib/src/domain/repository/quran/quran_download_repository.dart
  lib/src/domain/repository/quran/quran_reading_repository.dart
  lib/src/helpers/quran_path_helper.dart
  lib/src/helpers/version_helper.dart
  lib/src/pages/quran/page/quran_mode_selection_screen.dart
  lib/src/pages/quran/page/quran_reading_screen.dart
  lib/src/pages/quran/widget/download_quran_popup.dart
  lib/src/pages/quran/widget/reading/quran_reading_page_selector.dart
  lib/src/state_management/quran/download_quran/download_quran_notifier.dart
  lib/src/state_management/quran/reading/quran_reading_notifer.dart
  lib/src/state_management/quran/reading/quran_reading_state.dart
  test/src/data/quran/quran_remote_data_source_test.dart
  test/unit/data_source/download_quran_local_data_source_test.dart
  test/unit/data_source/download_quran_remote_data_source_test.dart
Labels: feature request

#1307 docs: Enhance Setup Documentation and Restructure Documentation Folder
  docs/quran/audio_playback_quran.md
  docs/quran/download_quran.md
  docs/quran/listening_quran.md
  docs/quran/reading_quran.md
  docs/setup/setup.md
  lib/docs/setup/setup.md
Labels: documentation

#1305 Fix/ No implementation found for method isPackageInstalled
  lib/src/helpers/TimeShiftManager.dart
Labels: bug

#1303 feat: Add favorite reciters functionality
  lib/l10n/intl_en.arb
  lib/src/const/constants.dart
  lib/src/data/data_source/quran/reciter_local_data_source.dart
  lib/src/data/repository/quran/recite_impl.dart
  lib/src/domain/error/recite_exception.dart
  lib/src/domain/repository/quran/recite_repository.dart
  lib/src/pages/SettingScreen.dart
  lib/src/pages/quran/page/reciter_selection_screen.dart
  lib/src/pages/quran/page/surah_selection_screen.dart
  lib/src/pages/quran/widget/quran_background.dart
  lib/src/pages/quran/widget/recite_type_grid_view.dart
  lib/src/pages/quran/widget/reciter_list_view.dart
  lib/src/state_management/quran/recite/recite_notifier.dart
  lib/src/state_management/quran/recite/recite_state.dart
  pubspec.yaml
  test/unit/data_source/recite_local_data_source_test.dart
Labels: feature request

#1333 fix: Update Hadith language API fetching
  lib/i18n/AppLanguage.dart
  lib/src/data/repository/random_hadith_impl.dart
  lib/src/pages/SettingScreen.dart
  lib/src/pages/home/workflow/normal_workflow.dart
  lib/src/state_management/random_hadith/random_hadith_notifier.dart
Labels: bug

#1335 fix: small font for salah timer in the grid
  lib/src/pages/home/sub_screens/AnnouncementScreen.dart
  lib/src/pages/home/widgets/salah_items/SalahItem.dart
  lib/src/pages/home/widgets/salah_items/responsive_mini_salah_bar_turkish_widget.dart
  lib/src/pages/home/widgets/salah_items/responsive_mini_salah_bar_widget.dart
Labels: bug
