Repository mawaqit/android-tv-app, pull requests merged in 2024-10, with the labels that each got.

#1328 feat: Add Switching Between Quran Warsh and Hafs
  lib/l10n/intl_en.arb
  lib/src/const/constants.dart
  lib/src/data/data_source/quran/download_quran_local_data_source.dart
  lib/src/data/data_source/quran/download_quran_remote_data_source.dart
  lib/src/data/data_source/quran/quran_reading_local_data_source.dart
  lib/src/data/repository/quran/quran_download_impl.dart
  lib/src/data/repository/quran/quran_reading_impl.dart
  lib/src/domain/model/quran/moshaf_type_model.dart
  lib/src/domain/repository/quran/quran_download_repository.dart
  lib/src/domain/repository/quran/quran_reading_repository.dart
  lib/src/helpers/no_internet_toast.dart
  lib/src/helpers/quran_path_helper.dart
  lib/src/pages/quran/page/quran_reading_screen.dart
  lib/src/pages/quran/widget/download_quran_popup.dart
  lib/src/pages/quran/widget/reading/moshaf_selector.dart
  lib/src/pages/quran/widget/switch_button.dart
  lib/src/state_management/quran/download_quran/download_quran_notifier.dart
  lib/src/state_management/quran/download_quran/download_quran_state.dart
  lib/src/state_management/quran/reading/moshaf_state.dart
  lib/src/state_management/quran/reading/moshaf_type_notifier.dart
  lib/src/state_management/quran/reading/quran_reading_notifer.dart
  lib/src/state_management/quran/reading/quran_reading_state.dart
  test/unit/data_source/download_quran_local_data_source_test.dart
  test/unit/data_source/download_quran_remote_data_source_test.dart
Labels: feature request

#1362 fix: RangeError in `ReciterListView`
  lib/src/pages/quran/widget/reciter_list_view.dart
Labels: bug

#1375 feat:improve Quran data caching mechanism
  lib/src/data/data_source/quran/quran_local_data_source.dart
  lib/src/data/repository/quran/quran_impl.dart
  lib/src/domain/error/quran_exceptions.dart
Labels: feature request

#1377 fix: update reciter box constant to resolve favorite reciter fetch issue
  lib/src/const/constants.dart
Labels: bug

#1376 fix: issue with filtering favorite reciters not updating after changes.
  lib/src/state_management/quran/recite/recite_notifier.dart
  lib/src/state_management/quran/recite/recite_state.dart
Labels: bug

#1364 add missing french strings
  lib/l10n/intl_fr.arb
Labels: translation

#1368 feat: add the reciter image at the play
  lib/src/pages/quran/page/quran_player_screen.dart
Labels: feature request

#1381 Update Polish language
  lib/l10n/intl_pl.arb
Labels: translation

#1380 Update Bulgarian Language
  lib/l10n/intl_bg.arb
Labels: translation
